name: Test

on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: 0

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup Python (using cached pip)
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: Pipfile.lock
          python-version-file: .python-version
      - name: Setup Python (using cached pipenv)
        uses: actions/setup-python@v4
        with:
          cache: 'pipenv'
          cache-dependency-path: Pipfile.lock
          python-version-file: .python-version
      - name: Install pipenv (pip install pipenv)
        run: pip install pipenv
      - name: Install dependencies using pipenv (pipenv sync --dev)
        run: pipenv sync --dev --verbose
      - name: Run Tests (pipenv run pytest)
        run: pipenv run pytest
